In [ ]:
#NumPy is a Python library for scientific computing.
#All elements in a NumPy array should be of the same type to allow mathematical operations.

#NumPy arrays are faster and more compact than Python lists.

In [1]:
import numpy as np

In [7]:
#a1 = np.array([1, 2, 3, 4, 5, 6]) # an array with some numbers
#print(a1[4]) # accessing the 3rd element of the array, note index starts from 0
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a2[1]) # access the 3rd element of the array

[5 6 7 8]


In [12]:
One2Ten = np.arange(11) # creates an array with numbers from 0 to 9

In [13]:
#print(One2Ten.shape) # shows array is rank 1 (one-dimensional)
One2Ten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
One2TenwithStep = np.arange(0,10,1.5) # create an array with step of 1.5

In [15]:
print(One2TenwithStep) # print to confirm

[0.  1.5 3.  4.5 6.  7.5 9. ]


In [17]:
AllZeros = np.zeros(10) # create an array with all zeroes 
print(AllZeros)
#AllOnes = np.ones(10) # create an array with all ones
#print(AllOnes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
AllZerosRank2 = np.zeros((10,2)) # create a rank 2 array with all zeroes
print(AllZerosRank2)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [22]:
#arrRan = np.random.random((2,4)) # 2D array with random values between 0.0 and 1.0
#print(arrRan)
arrRan.size # find the total number of elements in the array

8

In [24]:
list1 = [8,7,6,5,4] # Create a NumPy array from a Python list
r1 = np.array(list1)
print(r1)

[8 7 6 5 4]


In [29]:
nums = np.arange(20) # examples showing how to select only odd even numbers from a numPy array
#print(nums)
#odd_nums = nums[nums % 2 == 1]
#print(odd_nums)
even_nums = nums[nums % 2 == 0]
print(even_nums)

[ 0  2  4  6  8 10 12 14 16 18]


In [35]:
#Changing an array from 1D to 2D

one = np.arange(16) # creates an array with 16 elements
two = np.reshape(one, (4,4)) # reshapes into a 4x4 array
#2D_array82 = np.reshape(1D_array, (8,2)) # reshapes into a 8x2 array
print(two)
#print(2D_array82)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [40]:
#Slicing arrays

new_array = np.arange(15) # creates an array with 15 elements
newer = np.reshape(new_array, (5,3)) # reshape to a 5x3 array
#print(newer)
sliced = newer[1:3,:3]
print(sliced)

[[3 4 5]
 [6 7 8]]


In [43]:
#NumPy Array math additon

x1 = np.arange(24,34)
y1 = np.arange(16,26)
print(x1)
print(y1)
#print(x1+y1) # add array elements
#np.add(x1+y1) # another way to add array elements

#print(x1-y1) # another way to subtract array elements 
#np.subtract(x1,y1)

#print(x1*y1) # multiply array elements
#np.multiply(x1,y1) # another way to multiply array elements

print(x1 / y1) # divide array elements
#np.divide(x1,y1) #another way to divide array elements


[24 25 26 27 28 29 30 31 32 33]
[16 17 18 19 20 21 22 23 24 25]
[1.5        1.47058824 1.44444444 1.42105263 1.4        1.38095238
 1.36363636 1.34782609 1.33333333 1.32      ]


In [45]:
# Finding unique numbers in an array

duplicates = np.array([10, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20, 10])
uniq_vals = np.unique(duplicates)
print(uniq_vals)

[10 11 12 13 14 15 16 17 18 19 20]


In [50]:
#Sorting numPy arrays

#numbers = np.array([56,98,4,31,16])
#numbers.sort()
#print(numbers) # numbers correctly sorted

prices = np.array([5.5,3.7,21.9,45.0,7.8])
print(prices.argsort()) # sort the array based on array index 

# The resulting output [1 0 4 2 3] shows the smallest (3.7) is in 2nd location of array, similarly next largest number (5.5)
# is in the first location and so on, very powerful when sorting across multiple arrays. 

[1 0 4 2 3]
